CREATE TABLE Users(
    ID INT PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    EMAIL TEXT NOT NULL,
    VI BOOLEAN NOT NULL
);
CREATE TABLE Messages(
    ID INT PRIMARY KEY NOT NULL,
    UserEmail TEXT,
    HelperEmail TEXT,
    MsgTYPE TEXT NOT NULL
);
